### ISSUE TITLE
Implement: files download

### ISSUE THREAD

**Issue by mwvaughn** [TACC-Cloud/tapis-cli-ng#180]
Add a "files download" command to tapis-cli

**Comment by mwvaughn** [comment]
In progress in 94ace9473d974061e9aac9bdf97376a909053474

**Comment by mwvaughn** [comment]
Released to testing 27-09-2019 cd383f6562cb1d5370d6ad8d9cc1c6baf185e9d0

**Comment by eho-tacc** [comment]
`tapis files download` raises `IsADirectoryError: [Errno 21] Is a directory: '.'` when Agave URI points to a file. Works as expected when URI points to a directory.

Line 188 in `v2/files/helpers/sync.py`, var `source` points to a file instead of its base directory. Propagates to `dest_names = ['.']` (line 188), `with open('.', 'wb) as dest_file:` (line 139).
