### ISSUE TITLE
Tapis upload doesn't work

### ISSUE THREAD

**Issue by stevenrbrandt** [TACC-Cloud/tapis-cli-ng#227]
**Describe the bug**
When I call upload, I get a message saying that 0 bytes are uploaded.

**To Reproduce**
Shown below. Note that the file does exist on my local machine.
```
jovyan:~$ tapis files upload agave://shelob-storage-tg457049/new-agave-deployment tapis_test_app-wrapper.txt
+-------------------+------------+
| Field             | Value      |
+-------------------+------------+
| uploaded          | 0          |
| skipped           | 0          |
| messages          | 1          |
| bytes_transferred | 0.00 bytes |
| elapsed_sec       | 1          |
+-------------------+------------+
jovyan:~$ ls -ld tapis_test_app-wrapper.txt
-rw-r--r-- 1 jovyan jovyan 180 Oct 29 15:48 tapis_test_app-wrapper.txt
```

**Expected behavior**
I expected the file to be uploaded.
Also, since I had these ENV variables set, I expected to see a curl command:
TAPIS_PY_SHOW_CURL=1
TAPIS_CLI_SHOW_CURL=1

**Screenshots**

**Desktop (please complete the following information):**
docker / ubuntu:18.04

**Additional context**
Latest version of tapis client was used.

**Comment by stevenrbrandt** [comment]
On digging in further, I discovered I can upload files if I unset TAPIS_PY_SHOW_CURL and TAPIS_CLI_SHOW_CURL

**Comment by stevenrbrandt** [comment]
However, I still can't upload files to a directory
```
jovyan:~$ tapis -v files upload agave://shelob-storage-tg457049/new-agave-deployment x
{
  "uploaded": [],
  "skipped": [],
  "messages": [
    "404 Client Error: Not Found for url: https://api.tacc.utexas.edu/files/v2/media/system/shelob-storage-tg457049//new-agave-deployment/"
  ],
  "bytes_transferred": 0,
  "elapsed_sec": 1
}
```

**Comment by mwvaughn** [comment]
There are two issues at work here:

The first is that the function which renders a curl command from a request is failing to deal with an edge case. That is likely to get fixed by the curlify authors, but illuminates the fact that a curlify error should not be breaking our code in the first place. I have [updated AgavePy](https://github.com/TACC/agavepy/commit/c2c7717eb6bed4d59a6f4a9ec559ae60a2c9ebb1) to wrap the curlify call in an Exception handler. I have also wrapped the cognate function in Tapis CLI the same way in 66f2aefd02260f73f5baa2666161a91e0a592026. 

The second is a little more complicated, but can be mitigated a bit by making the Tapis error responses more verbose. This was accomplished via [another change to AgavePy](https://github.com/TACC/agavepy/commit/867b08cf839f523d0a327d0c7fc0ae688b6272f8)

**Comment by stevenrbrandt** [comment]
@mwvaughn is it understood why I can only upload to my home dir and not a subdir? I can upload to a subdir using a hand-crafted curl.

**Comment by stevenrbrandt** [comment]
@mwvaughn it seems I can upload to the subdir if I specify the full path name on the remote machine.
```
tapis -v files upload agave://shelob-storage-tg457049//home/funwave/new-agave-deployment x
```
works but
```
tapis -v files upload agave://shelob-storage-tg457049/new-agave-deployment x
```
does not. Is that expected?

**Comment by mwvaughn** [comment]
I think we've resolved this via offline conversations and some improvements to the underlying AgavePy library, so I am closing this issue.
