### ISSUE TITLE
Execute tapis operations without the leading agave:// uri

### ISSUE THREAD

**Issue by rstijerina** [TACC-Cloud/tapis-cli-ng#237]
It would be nice to simply execute ```tapis files list <system_id>```,  instead of ```tapis files list agave://<system_id``` but if this was intentional I'd be curious to know why.

**Comment by mwvaughn** [comment]
Thanks for the feedback!

I will say this is an intentional design decision, with a few justifications. For a simple listing operation, it seems a bit cumbersome I agree, but as soon as we start using commands that bridge Tapis with either the local environment or other platforms, it gets complicated. 

In terms of justification:
1. Based on several years' experience supporting end users of the files API, we've found a major source of confusion to come from having to specify both the system ID and the path at all, especially if they come from tenants where there is (initially at least) but a single shared storage system. We need to really advance the idea that bucket AND path must be specified because default systems are an idea that I hope is going to go away in V3. As one of the original designers of the files API,  it is my opinion that said feature was a design mistake. 
2. It is consistent with industry practice. The closest functional analog to Tapis' system + path are S3 buckets and paths. When we look at how various AWS and Google Cloud CLI tools interact with these entities, it is universal to use `<protocol>://<bucket>[</path>]`. Examples include `gsutil ls gs://my-bucket/images` and `aws s3 ls s3://my-bucket/images`. 
3. Job requests (and some other functions) use agave-canonical URIs. We want to advance the end user's understanding and familiarity with these. There is also planned support for the `AgaveURI` class to handle the `http(s)` form that is returned in the hypermedia slot of files and jobs listings. 
4. This is a future-looking design. It is intended that files management functions in the CLI can (or will) work with non-Tapis references. Requiring the `agave` slug greatly simplifies the implementation of features with syntax such as:

```
# Currently managed by the standalone 'tapis files upload'
tapis files copy local/file.txt agave://my-bucket/uploads
# Currently managed by standalone 'tapis files download'
tapis files copy agave://my-bucket/images/ local/media
# Destination as agave URL not supported yet
tapis files copy agave://your-bucket/uploads/file.txt agave://my-bucket/documents/file.txt
tapis files move agave://your-bucket/uploads/file.txt agave://my-bucket/documents/file.txt
# Swinging for the fences here but planning to pursue this
tapis files copy s3://my-amazon-bucket/file.csv agave://my-bucket/file.csv
```

Hopefully, this shines some light on the current thought process and implementation. I'm happy to discuss further!
